Repository TeamMODOO/FE, pull requests merged in 2024-12, with the labels that each got.

#3 💄 Design(#2): 맵 배경 구현
  public/background/Lobby.webp
  public/background/MeetingRoom.webp
  public/background/Myroom.webp
  src/app/lobby/_component/Canvas.style.ts
  src/app/lobby/_component/Canvas.tsx
  src/app/lobby/page.tsx
  src/app/meetingroom/[id]/_component/Canvas.style.ts
  src/app/meetingroom/[id]/_component/Canvas.tsx
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[id]/_component/Canvas.style.ts
  src/app/myroom/[id]/_component/Canvas.tsx
  src/app/myroom/[id]/page.tsx
Labels: 💄 Design

#5 ✨ Feat(#4): 맵에 캐릭터 렌더링 기능 구현
  public/character/character1.png
  public/character/character2.png
  src/app/lobby/_component/Canvas.tsx
  src/app/lobby/_component/CharacterArray.tsx
  src/app/lobby/_model/User.ts
  src/app/meetingroom/[id]/_component/Canvas.tsx
  src/app/meetingroom/[id]/_component/CharacterArray.tsx
  src/app/meetingroom/[id]/_model/User.ts
  src/app/myroom/[id]/_component/Canvas.tsx
  src/app/myroom/[id]/_component/CharacterArray.tsx
  src/app/myroom/[id]/_model/User.ts
Labels: ✨ Feat

#20 💄 Design: 로그인 화면 디자인 추가
  public/background/SignIn.png
  src/app/signin/SignInpage.module.css
  src/app/signin/page.tsx
Labels: 💄 Design

#43 🚑️ Fix(#42): 움직임 소켓 연결 버그 수정
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/hooks/useLobbySocketEvents.ts
  src/hooks/useMainSocketConnect.tsx
  src/hooks/useMovementSocket.tsx
  src/store/useUsersStore.tsx
Labels: 🚑️ Fix

#46 🔨 Refactor(#45): 아바타 생성 기능 삭제
  src/app/api/generate-avatar/route.ts
  src/app/registeravatar/RegisterAvatar.module.css
  src/app/registeravatar/page.tsx
Labels: 🔨 Refactor

#49 🔨 Refactor(#48): 소켓 url 변경"
  src/hooks/useMainSocketConnect.tsx
Labels: 🔨 Refactor

#55 💄 Design(#54): /questmap 이미지 파일 추가 및 수정
  public/background/QuestComplete.webp
  public/background/QuestMap.webp
  public/character/npc4.webp
  src/app/questmap/QuestComplete.module.css
Labels: 💄 Design

#58 ✨ Feat(#56): /questmap 순위 출력 기능 NPC 모달 기능 작업
  src/app/questmap/QuestMap.module.css
  src/app/questmap/_component/RankingModal/RankingModal.module.css
  src/app/questmap/_component/RankingModal/RankingModal.tsx
  src/app/questmap/page.tsx
Labels: ✨ Feat, 💄 Design

#61 🔨 Refactor(#60): 백준 문제풀이 채점 프롬프트 보완
  src/app/api/check-answer/route.ts
Labels: 🔨 Refactor

#65 ✨ Feat(#57): 퀘스트 맵 및 움직임 구현
  src/app/myroom/[id]/_component/Canvas/Canvas.tsx
  src/app/questmap/_component/Npc/NpcList.style.ts
  src/app/questmap/_component/Npc/NpcList.tsx
  src/app/questmap/_component/Npc/NpcModal.style.ts
  src/app/questmap/_component/Npc/NpcModal.tsx
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.style.ts
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
  src/app/questmap/_model/User.ts
  src/app/questmap/page.tsx
  src/hooks/useQuestMapSocketEvents.ts
Labels: ✨ Feat

#63 ✨ Feat(#40): webRTC 구현
  package.json
  public/svg/file.svg
  public/svg/globe.svg
  public/svg/next.svg
  public/svg/vercel.svg
  public/svg/window.svg
  src/app/Canvas/_component/CanvasSection.tsx
  src/app/Canvas/_component/ColorPanel.tsx
  src/app/Canvas/_component/Toolbar.tsx
  src/app/Canvas/constant/colorCode.ts
  src/app/Canvas/page.tsx
  src/app/RTC/_components/ChatWidget.tsx
  src/app/RTC/_components/Header.tsx
  src/app/RTC/_components/LocalVideo.tsx
  src/app/RTC/_components/MediaStateIndicators.tsx
  src/app/RTC/_components/PeerMedia.tsx
  src/app/RTC/_components/RemoteMedia.tsx
  src/app/RTC/_components/RoomJoinForm.tsx
  src/app/RTC/_hook/useMediaAttachments.ts
  src/app/RTC/_model/webRTC.type.ts
  src/app/RTC/page.tsx
  src/app/layout.tsx
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/app/lobby/page.tsx
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[id]/_component/Canvas/Canvas.tsx
  src/app/page.tsx
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
  src/app/questmap/page.tsx
  src/components/chat/lobby/chatMessages.tsx
  src/components/chat/lobby/listMessages.tsx
  src/components/index.ts
  src/components/sideBar/homeSideBar.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/components/ui/popover.tsx
  src/components/ui/tooltip.tsx
  src/hooks/chat/useChatScroll.ts
  src/hooks/chat/useChatSocket.ts
  src/hooks/performance/useDebounce.ts
  src/hooks/performance/useThrottle.ts
  src/hooks/socket/useAudioSocketConnect.ts
  src/hooks/socket/useMainSocketConnect.ts
  src/hooks/useMobile.tsx
  src/store/useAudioSocketStore.ts
  src/store/useCanvasStore.ts
  src/store/useMainSocketStore.ts
  src/store/useToolStore.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feat

#70 ✨ Feat(#69): /questmap 에서 랭킹 출력 모달 띄우기
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
Labels: ✨ Feat

#74 ✨ Feat(#64) Google Login API 연결부 작성
  src/app/lobby/page.tsx
  src/auth.ts
  src/hooks/signin/useSignIn.ts
Labels: ✨ Feat

#77 💄 Design(#75): 맵 크기를 현재 기기의 화면 크기에 맞도록 조정
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/app/lobby/_component/MapConstants.ts
  src/app/myroom/[id]/_component/Canvas/Canvas.tsx
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
  src/hooks/chat/useChatSocket.ts
Labels: 💄 Design

#83 🚑️ Fix(#66): webRTC 버그 수정
  Dockerfile
  package.json
  src/app/RTC/page.tsx
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/app/lobby/_component/EnterMeetingRoom/EnterMeetingRoom.tsx
  src/app/lobby/_component/EnterMeetingRoom/Room.tsx
  src/app/meetingroom/[id]/_component/Canvas.style.ts
  src/app/meetingroom/[id]/_component/Canvas.tsx
  src/app/meetingroom/[id]/_component/CharacterArray.ts
  src/app/meetingroom/[id]/_component/webRTC.tsx
  src/app/meetingroom/[id]/_components/ChatWidget.tsx
  src/app/meetingroom/[id]/_components/Header.tsx
  src/app/meetingroom/[id]/_components/LocalVideo.tsx
  src/app/meetingroom/[id]/_components/MediaStateIndicators.tsx
  src/app/meetingroom/[id]/_components/PeerMedia.tsx
  src/app/meetingroom/[id]/_components/RemoteMedia.tsx
  src/app/meetingroom/[id]/_components/RoomJoinForm.tsx
  src/app/meetingroom/[id]/_hook/useMediaAttachments.ts
  src/app/meetingroom/[id]/_model/User.ts
  src/app/meetingroom/[id]/_model/webRTC.type.ts
  src/app/meetingroom/[id]/page.tsx
  yarn.lock
Labels: 🚑️ Fix

#84 ✨ Feat(#66): MAP_CONSTANTS 추가
  src/app/lobby/_component/Canvas/Canvas.tsx
Labels: ✨ Feat
