Repository TeamMODOO/FE, pull requests merged in 2025-01, with the labels that each got.

#96 🔨 Refactor(#89): yarn build 에러 수정
  src/app/lobby/_component/Canvas/Canvas.tsx
Labels: 🔨 Refactor

#101 🚑️ Fix(#100): 소켓 중복 연결 제거
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/app/lobby/page.tsx
  src/app/myroom/[id]/_component/Canvas/Canvas.tsx
  src/app/myroom/[id]/page.tsx
  src/app/questmap/_component/QuestMapCanvas/QuestMapCanvas.tsx
Labels: 🚑️ Fix

#103 🚑️ Fix(#102): 백준 문제풀이 화면에 이미지 로딩 후 애니메이션 보여지도록 수정
  src/app/quest/Quest.module.css
  src/app/quest/page.tsx
Labels: 🚑️ Fix

#106 🚑️ Fix: 용 잔상 현상 해결
  src/app/quest/Quest.module.css
  src/app/quest/page.tsx
Labels: 🚑️ Fix

#109 🚑️ Fix(#108): 움직임 부분 소켓 연결 버그 수정
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
  src/store/useUsersStore.tsx
Labels: 🚑️ Fix

#116 🚑️ Fix: 백준 문제 풀이 페이지 버튼이 안눌리는 버그 수정
  src/app/quest/Quest.module.css
  src/app/quest/page.tsx
Labels: 🚑️ Fix

#117 🚑️ Fix(#114): 메인 로비 소켓 프로토콜에 user_name 추가
  src/app/lobby/_component/Canvas/Canvas.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
  src/store/useUsersStore.tsx
Labels: 🚑️ Fix

#123 ✨ Feat(#122): 소켓 서버 프로토콜 변경에 따른 useMainSocketConnect 코드 변경
  src/hooks/socket/useMainSocketConnect.ts
Labels: ✨ Feat

#127 🚑️ Fix(#126): 배포시 소켓 움직임 부분 닉네임 버그 수정
  src/hooks/socket/useMainSocketConnect.ts
Labels: 🚑️ Fix

#131 🔨 Refactor: Google Auth Login 자체 API 재수정
  src/app/lobby/page.tsx
  src/hooks/signin/useSignIn.ts
  src/hooks/signin/useSignInPost.ts
Labels: 🔨 Refactor

#136 🔨 Refactor: API 서버 baseURL 환경변수 추출
  src/hooks/signin/useSignInPost.ts
Labels: 🔨 Refactor

#142 ✨ Feat(#140): 타자 연습 싱글 모드 추가
  src/app/typing/_component/TypingCompleteModal/TypingCompleteModal.module.css
  src/app/typing/_component/TypingCompleteModal/TypingCompleteModal.tsx
  src/app/typing/page.tsx
  src/app/typing/typing.module.css
Labels: ✨ Feat

#149 🚑️ Fix(#148): 백준 문제 풀이 후 Invalid JSON 오류 픽스
  src/app/api/check-answer/route.ts
Labels: 🚑️ Fix

#160 🚑️ Fix(#158): 소켓 프로토콜에 맞게 메인 로비 코드 수정
  src/app/lobby/_component/Canvas/LobbyCanvas.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
  src/store/useUsersStore.ts
Labels: 🚑️ Fix

#161 🚑️ Fix(#159): 로그인 시 API 요청 과다 문제 픽스
  src/app/signinloading/page.tsx
Labels: 🚑️ Fix

#162 hotfix
  src/app/myroom/[google_id]/_component/BoardModal/BoardModal.tsx
Labels: 🚑️ Fix

#165 ✨ Feat(#158): Patch API에 withCredentials 속성 추가
  src/queries/myroom/usePatchMyRoomOwnerProfile.ts
Labels: ✨ Feat

#166 ✨ Feat(#163): 마이룸 방명록 API 작업 (GET)
  src/app/myroom/[google_id]/_component/BoardModal/BoardModal.tsx
  src/hooks/myroom/useGuestBookGet.ts
Labels: ✨ Feat

#168 ✨ Feat(#163): 마이룸 방명록 API 작업 (비밀글 기능 보류, 작성 후 새로 불러오기)
  src/app/myroom/[google_id]/_component/BoardModal/BoardModal.tsx
Labels: 🔨 Refactor

#171 🚑️ Fix(#170): 마이룸 api 표시 버그 수정
  src/app/myroom/[google_id]/_component/Canvas/MyRoomCanvas.tsx
  src/app/myroom/[google_id]/_component/FurnitureInfoModal/FurnitureInfoModal.tsx
  src/app/myroom/[google_id]/page.tsx
Labels: 🚑️ Fix

#173 🚑️ Fix(#172): 마이룸 이력서 PDF PATCH 오류 수정
  src/app/myroom/[google_id]/_component/Canvas/MyRoomCanvas.tsx
  src/queries/myroom/usePatchMyRoomOwnerProfile.ts
Labels: 🚑️ Fix

#180 ✨ Feat(#174): 메인 로비에서 움직임 관련 소켓 추가 패킷 연결
  src/app/lobby/_component/Canvas/LobbyCanvas.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
Labels: ✨ Feat

#189 🚑️ Fix(#188): [hotfix] middleware
  src/middleware.ts
Labels: 🚑️ Fix

#190 Fix(#188): [hotfix] middleware_re
  src/middleware.ts
Labels: 🚑️ Fix

#193 🚑️ Fix(#192): 배포시 생기는 로그인 문제 수정
  package.json
  src/app/signinloading/page.tsx
  src/middleware.ts
  yarn.lock
Labels: 🚑️ Fix

#195 ✨ Feat(#181): 비회원 상태에서 컨텐츠 접근 시 모달 출력, 미들 웨어 버그 픽스
  package.json
  src/app/layout.tsx
  src/app/lobby/_component/Canvas/LobbyCanvas.tsx
  src/app/quest/_component/QuestSection/page.tsx
  src/components/modal/NeedSignIn/NeedSignInModal.module.css
  src/components/modal/NeedSignIn/NeedSignInModal.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/middleware.ts
  yarn.lock
Labels: ✨ Feat, 🚑️ Fix

#218 ✨ Feat(#217): 메인 로비 이미지 변경 및 충돌처리 구현
  public/background/myroom.png
  public/character/npc5.png
  public/character/npc6.png
  public/furniture/portal.gif
  public/furniture/portal.png
  src/app/lobby/_components/Canvas/Canvas.style.ts
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_components/Portal/PortalList.tsx
  src/app/lobby/_components/Portal/Potal.tsx
  src/app/lobby/_constant/index.ts
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
  src/app/myroom/[google_id]/_constant/index.ts
  src/app/questmap/_constant/index.ts
  src/hooks/lobby/useLobbyRenderer.ts
  src/hooks/myroom/useMyRoomKeyboard.ts
  src/hooks/myroom/useMyRoomRenderer.ts
  src/model/Funiture.ts
Labels: ✨ Feat

#220 ✨ Feat(#207): 소켓 로직 수정
  .eslintrc.json
  .vscode/settings.json
  next.config.mjs
  public/background/lobby_image.webp
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_components/EnterMeetingRoom/EnterMeetingRoom.tsx
  src/app/lobby/_components/Widget/FriendInformation.tsx
  src/app/lobby/page.tsx
  src/app/meetingroom/[id]/_components/canvas/CanvasSection.tsx
  src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts
  src/app/meetingroom/[id]/_hook/useMeetingRoom.ts
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[google_id]/page.tsx
  src/app/quest/_components/QuestSection/page.tsx
  src/app/questmap/page.tsx
  src/hooks/chat/useChatSocket.ts
  src/hooks/lobby/useLobbySocketEvents.ts
  src/hooks/myroom/useMyRoomSocketEvents.ts
  src/hooks/socket/useMainSocketConnect.ts
  src/model/socket.ts
  src/provider/index.tsx
  src/provider/socket-provider.tsx
  src/queries/lobby/useUserQuery.ts
  src/store/useClientIdStore.ts
  src/store/useMainSocketStore.ts
  src/store/useSocketStore.ts
Labels: ✨ Feat

#222 🔨 Refactor: 새로고침 했을 때 소켓 연결 끊기
  src/provider/socket-provider.tsx
Labels: 🔨 Refactor

#237 Feat(#233): 문제 풀이 화면 효과음 수정, 랭킹 모달 수정, 미니게임 임시 추가
  public/minigames/minigame1.png
  public/minigames/minigame2.png
  public/minigames/minigame3.png
  public/npc_event/firstmedal.png
  public/npc_event/secondmedal.png
  public/npc_event/thirdmedal.png
  public/sounds/correctFx.wav
  public/sounds/incorrectFx.wav
  public/sounds/swordSFX.wav
  src/app/lobby/_components/DailyProblem/DailyProblemContent.tsx
  src/app/pingpong/page.tsx
  src/app/quest/_components/QuestSection/page.tsx
  src/app/quest/page.tsx
  src/app/questmap/_components/RankingModal/RankingModal.module.css
  src/app/questmap/_components/RankingModal/RankingModal.tsx
  src/app/tetris/page.tsx
  src/app/typing/page.tsx
  src/app/typing/typing.module.css
  src/components/bgMusic/BgMusicButton.tsx
  src/components/gameRuleModal/GameRuleModal.module.css
  src/components/gameRuleModal/GameRuleModal.tsx
  src/components/outButton/OutButton.tsx
  src/components/pingpong/Game.tsx
  src/components/tetris/Board.module.css
  src/components/tetris/Board.tsx
  src/components/tetris/NextBlock.tsx
  src/components/tetris/Popup.tsx
  src/components/tetris/Score.tsx
  src/components/tetris/utils.ts
  src/utils/blocks.ts
  src/utils/tetrisLogic.ts
Labels: ✨ Feat, 💄 Design

#242 🚑️ Fix(#241): 메인 로비 움직임 가속 버그 해결
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_constant/index.ts
  src/hooks/lobby/useLobbyRenderer.ts
  src/hooks/lobby/useLobbySocketEvents.ts
  src/store/useUsersRef.ts
Labels: 🚑️ Fix

#244 🚑️ Fix(#243): 메인 로비 움직임 가속 버그 수정 및 속도 변경
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_constant/index.ts
Labels: 🚑️ Fix

#251 🚑️ Fix: hotfix
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
Labels: 🚑️ Fix

#255 🚑️ Fix: 맥북 채팅 두번 보내지는 버그 수정
  src/components/chat/left/LeftChatWidget.tsx
  src/components/chat/right/RightChatWidget.tsx
  src/hooks/chat/useChatSocket.ts
Labels: 🚑️ Fix

#258 🚑️ Fix: 마이룸 API 함수 호출 픽스
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
Labels: 🚑️ Fix

#264 🚑️ Fix(#262): 오타 수정
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[google_id]/page.tsx
Labels: 🚑️ Fix

#268 🚑️ Fix(#267): hotfix
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/page.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
  src/store/useUsersRef.ts
Labels: 🚑️ Fix

#276 💄 Design(#271): 마이룸, 메인로비에서 캐릭터 랜더링 크기 변경 및 배경 이미지 크기 수정
  public/sprites/man.png
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_constant/index.ts
  src/app/lobby/page.tsx
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
  src/app/myroom/[google_id]/_constant/index.ts
  src/app/myroom/[google_id]/page.tsx
  src/hooks/lobby/useLobbyKeyboard.ts
  src/hooks/lobby/useLobbyRenderer.ts
  src/hooks/myroom/useMyRoomKeyboard.ts
  src/hooks/myroom/useMyRoomRenderer.ts
  src/hooks/performance/useLoadSprites.ts
Labels: 💄 Design

#278 💄 Design(#277): 마이룸 기술스택 svg 맵핑 및 디자인 수정
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
  src/app/myroom/[google_id]/_components/TechStackModal/TechStackModal.tsx
  src/app/myroom/[google_id]/_constant/index.ts
  src/hooks/myroom/useMyRoomRenderer.ts
Labels: 💄 Design

#281 ✨ Feat(#279): 마이룸 움직임 보간, 메인로비 움직임 로직 변경, favicon 수정
  public/favicon/favicon.ico
  public/favicon/favicon.png
  src/app/layout.tsx
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_constant/index.ts
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
  src/app/myroom/[google_id]/_constant/index.ts
  src/hooks/myroom/useMyRoomRenderer.ts
  src/middleware.ts
Labels: ✨ Feat

#284 🚑️ Fix(#283): 메인 로비 움직임 시간 기반이 아닌 프레임 기반으로 움직이도록 설정 되돌리기
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/_constant/index.ts
Labels: 🚑️ Fix

#293 ✨ Feat(#286): 포폴 여러개 등록
  src/app/meetingroom/[id]/_components/Header.tsx
  src/app/meetingroom/[id]/_components/canvas/CanvasSection.tsx
  src/app/meetingroom/[id]/_components/canvas/ColorPanel.tsx
  src/app/meetingroom/[id]/_components/canvas/PenSizePanel.tsx
  src/app/meetingroom/[id]/_components/canvas/Toolbar.tsx
  src/app/meetingroom/[id]/_components/video/MediaStateIndicators.tsx
  src/app/myroom/[google_id]/_components/Canvas/MyRoomCanvas.tsx
  src/components/chat/left/LeftChatInputArea.tsx
  src/components/chat/left/LeftChatMessage.tsx
Labels: ✨ Feat

#298 🚑️ Fix(#297): 메인 페이지 토글 버튼 단축키 중복 입력 처리 픽스
  src/app/lobby/_components/Widget/FriendInformation.tsx
  src/app/lobby/page.tsx
  src/components/bgMusic/BgMusicButton.tsx
Labels: 🚑️ Fix

#300 ✨ Feat(#296): 이미지 프리패치, 소켓 패킷 추가
  public/background/Myroom.webp
  public/background/quest_map.webp
  public/background/sheet.png
  public/character/character1.png
  public/character/character2.png
  public/character/npc4.webp
  public/interior/none.gif
  public/interior/none.webp
  public/interior/portfolio/portfolio1.gif
  public/interior/portfolio/portfolio2.gif
  public/interior/portfolio/portfolio3.gif
  public/interior/resume/resume.png
  public/interior/resume/resume1.gif
  public/interior/technologyStack/technologyStack1.gif
  public/interior/technologyStack/technologyStack2.gif
  public/interior/technologyStack/technologyStack3.gif
  public/interior/technologyStack/technologyStack4.gif
  public/interior/technologyStack/technologyStack5.gif
  public/interior/technologyStack/technologyStack6.gif
  public/interior/technologyStack/technologyStack7.gif
  public/interior/technologyStack/technologyStack8.gif
  public/interior/technologyStack/technologyStack9.gif
  src/app/api/check-answer/route.ts
  src/app/layout.tsx
  src/app/lobby/_components/Canvas/LobbyCanvas.tsx
  src/app/lobby/page.tsx
  src/app/meetingroom/[id]/page.tsx
  src/app/myroom/[google_id]/_constant/index.ts
  src/app/myroom/[google_id]/page.tsx
  src/app/typing/page.tsx
  src/components/PrefetchManager.tsx
  src/components/redundantModal/RedundantModal.tsx
  src/hooks/lobby/useLobbySocketEvents.ts
  src/hooks/signin/useSignInPost.ts
  src/hooks/socket/useAudioSocketConnect.ts
  src/model/socket.ts
  src/queries/lobby/useNoticeDetailQuery.ts
  src/queries/lobby/useNoticesQuery.ts
  src/queries/myroom/getName.ts
  src/queries/myroom/useMyRoomOwnerProfile.ts
  src/queries/myroom/usePatchMyRoomOwnerProfile.ts
  src/store/useSocketStore.ts
  src/store/useUsersRef.ts
Labels: ✨ Feat

#303 🚑️ Fix: hotfix
  src/app/lobby/page.tsx
  src/components/PrefetchManager.tsx
  src/hooks/chat/useChatSocket.ts
Labels: 🚑️ Fix

#308 🚑️ Fix: 이전 커밋으로 되돌리기
  src/hooks/socket/useAudioSocketConnect.ts
Labels: 🔨 Refactor, 🚑️ Fix

#319 ✨ Feat: 캠버스 첫유저 동기화
  src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts
Labels: ✨ Feat

#320 🚑️ Fix(#318): canvas 처음 방문 유저 동기화
  src/app/meetingroom/[id]/_hook/canvas/useCanvasSocket.ts
Labels: 🚑️ Fix

#321 📚 Docs: 1차 README 작성
  README.md
Labels: 📚 Docs

#322 Docs(#317): 2차 README 작성
  README.md
Labels: 📚 Docs
